# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Publish NuGet CQRS
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Perigee.Framework.Data.Cqrs/Perigee.Framework.Data.Cqrs.csproj
        PACKAGE_NAME: Perigee.Framework.Data.Cqrs
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        NUGET_SOURCE: https://api.nuget.org

    - name: Publish NuGet EF
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Perigee.Framework.Data.EntityFramework/Perigee.Framework.Data.EntityFramework.csproj
        PACKAGE_NAME: Perigee.Framework.Data.EntityFramework
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        NUGET_SOURCE: https://api.nuget.org

    - name: Publish NuGet Shared
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Perigee.Framework.Data.Helpers.Shared/Perigee.Framework.Data.Helpers.Shared.csproj
        PACKAGE_NAME: PerigeePerigee.Framework.Data.Helpers.Shared
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        NUGET_SOURCE: https://api.nuget.org

    - name: Publish NuGet Services
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Perigee.Framework.Data.Services/Perigee.Framework.Data.Services.csproj
        PACKAGE_NAME: PerigeePerigee.Framework.Data.Services
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        NUGET_SOURCE: https://api.nuget.org

    - name: Publish NuGet Web
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Perigee.Framework.Data.Web/Perigee.Framework.Data.Web.csproj
        PACKAGE_NAME: PerigeePerigee.Framework.Data.Web
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        NUGET_SOURCE: https://api.nuget.org
